# Generated by Django 4.2.1 on 2023-07-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_profile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profiles/user-default.jpg",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
