# Generated by Django 4.2.11 on 2024-03-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bba_admin', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
