# Generated by Django 4.2.11 on 2024-03-18 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bba_admin', '0005_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='loc_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
