# Generated by Django 4.2.11 on 2024-03-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bba_admin', '0007_alter_blog_long_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='parent_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='parent_last_name',
            new_name='last_name',
        ),
    ]
